import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ChevronRight } from "lucide-react";
import { Card, CardContent } from "../components/ui/card";
import SEOHead, { breadcrumbSchema } from "../components/SEOHead";

const sections = [
  {
    title: "Definitions and Key Terms",
    content: `To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, they are strictly defined as:

• Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.

• Company: when this policy mentions "Company", "we", "us", or "our", it refers to Samaria Gorge team, that is responsible for your information under this Disclaimer.

• Service: refers to the service provided by Samaria Gorge team as described in the relative terms (if available) and on this platform.

• Website: Samaria Gorge team's site, which can be accessed via this URL: https://samaria-gorge.gr/

• You: a person or entity that is registered with Samaria Gorge to use the Services.`
  },
  {
    title: "Limited Liability",
    content: "Samaria Gorge team endeavours to update and/or supplement the content of the website on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect. The materials offered on the website are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from Samaria Gorge team. Particularly, all prices on the website are stated subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors."
  },
  {
    title: "Links to Other Websites Disclaimer",
    content: "This Disclaimer applies only to the Services. The Services may contain links to other websites not operated or controlled by Samaria Gorge team. We are not responsible for the content, accuracy or opinions expressed in such websites. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy and Terms of every site you visit."
  },
  {
    title: "Errors and Omissions Disclaimer",
    content: "Samaria Gorge team is not responsible for any content, code or any other imprecision. Samaria Gorge team does not provide warranties or guarantees. In no event shall Samaria Gorge team be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service or the contents of the Service."
  },
  {
    title: "General Disclaimer",
    content: "The Samaria Gorge Service and its contents are provided \"as is\" and \"as available\" without any warranty or representations of any kind, whether express or implied. Samaria Gorge team is a distributor and not a publisher of the content supplied by third parties; as such, Samaria Gorge team exercises no editorial control over such content."
  },
  {
    title: "Copyright Disclaimer",
    content: "All intellectual property rights concerning these materials are vested in Samaria Gorge team. Copying, distribution and any other use of these materials is not permitted without the written permission of Samaria Gorge team, except and only to the extent otherwise provided in regulations of mandatory law."
  },
  {
    title: "Affiliate Links Disclosure",
    content: "Samaria Gorge has affiliate links and in this section of the Disclaimer we will address how we use those affiliate links from other websites/companies and products. Any/all of the links on Samaria Gorge are affiliate links of which we receive a small commission from sales of certain items, but the price is the same for you. If we post an affiliate link to a product, it is something that we personally use, support and would recommend without an affiliate link."
  },
  {
    title: "Fitness Disclosure",
    content: "The information on this website such as text, graphics, images, and other materials is intended solely for informational purposes and may not be used as a substitute for professional advice. Regular exercise is not always without risk, even for healthy individuals. To reduce the risk of injury, before beginning this or any exercise program, please consult a healthcare provider for appropriate exercise prescription and safety precautions."
  },
  {
    title: "Your Consent",
    content: "By using our website, registering an account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms."
  },
];

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background">
      <SEOHead
        title="Disclaimer — Samaria Gorge"
        description="Disclaimer and terms of use for the Samaria Gorge website. Information about limited liability, affiliate links, and fitness disclosures."
        canonical="/Disclaimer.html"
        noIndex={false}
        jsonLd={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "Disclaimer", path: "/Disclaimer.html" }])}
      />

      {/* Header */}
      <div className="bg-primary text-primary-foreground pt-28 pb-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-2 mb-4">
            <Link to="/" className="text-primary-foreground/60 text-sm font-body hover:text-primary-foreground transition-colors">Home</Link>
            <ChevronRight className="w-3.5 h-3.5 text-primary-foreground/40" />
            <span className="text-primary-foreground/90 text-sm font-body">Disclaimer</span>
          </div>
          <h1 className="font-display font-bold text-4xl text-primary-foreground">Disclaimer</h1>
          <p className="text-primary-foreground/65 font-body mt-2 text-sm">Updated at 2021-08-01</p>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <p className="text-base text-muted-foreground font-body leading-relaxed mb-10">
            Samaria Gorge team hereby grants you access to{" "}
            <Link to="/" className="text-primary hover:underline">samaria-gorge.gr</Link>{" "}
            ("the Website") and invites you to use/purchase the services offered here.
          </p>

          <div className="space-y-8">
            {sections.map((section, i) => (
              <Card key={i} className="bg-card border-border shadow-card">
                <CardContent className="p-6">
                  <h2 className="font-display font-semibold text-xl text-foreground mb-4">
                    {section.title}
                  </h2>
                  <div className="text-sm text-muted-foreground font-body leading-relaxed whitespace-pre-line">
                    {section.content}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          <Card className="mt-10 bg-primary/5 border-primary/15 shadow-card">
            <CardContent className="p-6">
              <h2 className="font-display font-semibold text-xl text-foreground mb-3">Contact Us</h2>
              <p className="text-sm text-muted-foreground font-body">
                Don't hesitate to contact us if you have any questions regarding this Disclaimer.
              </p>
              <a
                href="mailto:info@samaria-gorge.gr"
                className="mt-3 inline-flex items-center gap-2 text-sm font-medium text-primary font-body hover:underline"
              >
                info@samaria-gorge.gr
              </a>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </div>
  );
}
